services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8080:8080"
    volumes:
      - ./test/config:/config
    command: "-V -D -c /config/websocket.cfg"

  nats-jwt:
    image: nats
    ports:
      - "4223:4222"
      - "8083:8080"
    volumes:
      - ./test/config:/config
    command: "-V -D -c /config/jwt.cfg"

  nats-jwt2:
    image: nats
    ports:
      - "4227:4222"
    volumes:
      - ./test/config:/config
    command: "-V -D -c /config/jwt2.cfg"

  nats-token:
    image: nats
    ports:
      - "4224:4222"
      - "8084:8080"
    volumes:
      - ./test/config:/config
    command: "-V -D -c /config/websocket.cfg --auth mytoken"

  nats-user:
    image: nats
    ports:
      - "4225:4222"
      - "8085:8080"
    volumes:
      - ./test/config:/config
    command: "-V -D -c /config/websocket.cfg --user foo --pass bar"

  nats-nkey:
    image: nats
    ports:
      - "4226:4222"
      - "8086:8080"
    volumes:
      - ./test/config:/config
    command: "-V -D -c /config/nkey.cfg"

  nats-tls:
    image: nats
    ports:
      - "4443:4222"
      - "8443:443"
    volumes:
      - ./test/config:/config
    command: "-V -D -c /config/wss.cfg --tls --tlscert=/config/server-cert.pem --tlskey=/config/server-key.pem"

