name: dart_to_nats
description: A Dart client for the NATS messaging system. Forked from [dart-nats](https://github.com/chartchuo/dart-nats).
version: 0.1.0
homepage: https://github.com/sty-holdings/dart_to_nats
repository: https://github.com/sty-holdings/dart_to_nats

environment:
  sdk: '>=2.15.0 <4.0.0'

# dependencies:

dev_dependencies:
  lints: ^2.0.1
  test: ^1.9.4
  # pedantic: ^1.11.0
dependencies: 
  base32: ^2.1.3
  # cryptography: ^2.0.5
  ed25519_edwards: ^0.3.1
  mutex: ^3.0.0
  web_socket_channel: ^2.2.0
